add_wave /tb_top/clk
add_wave /tb_top/rst_n
add_wave /tb_top/wrapper_i/top_i/core_i/pc_id
add_wave /tb_top/wrapper_i/top_i/core_i/instr_rdata_id
add_wave /tb_top/wrapper_i/top_i/core_i/mhpmevent_minstret
add_wave /tb_top/wrapper_i/top_i/core_i/mhpmevent_load
add_wave /tb_top/wrapper_i/top_i/core_i/mhpmevent_store
add_wave /tb_top/wrapper_i/top_i/core_i/mhpmevent_branch
add_wave /tb_top/wrapper_i/top_i/core_i/mhpmevent_jump
add_wave /tb_top/wrapper_i/top_i/core_i/alu_en_ex
add_wave /tb_top/wrapper_i/top_i/core_i/mult_en_ex
add_wave /tb_top/wrapper_i/top_i/core_i/csr_access_ex
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/arithmetic_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/logic_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/memory_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/branch_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/jump_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/floating_q
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/alu_arithmetic
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/alu_logic
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/memory_insn
add_wave /tb_top/wrapper_i/top_i/core_i/insn_classifier_i/non_alu_category
run 0 ns
